# Generated by Django 5.1 on 2025-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('profile_pic', models.FileField(upload_to='Media')),
                ('address', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=2)),
            ],
        ),
    ]
