# Generated by Django 5.1 on 2025-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='address_line',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.FileField(default=None, upload_to='Media'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
