# Generated by Django 5.1 on 2025-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0002_remove_usermodel_address_usermodel_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
    ]
