# Generated by Django 5.1 on 2025-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0004_alter_usermodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address_line',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='Media'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
