# Generated by Django 5.1 on 2025-05-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0005_alter_usermodel_address_line_alter_usermodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pincode',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
