# Generated by Django 5.1 on 2025-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0009_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
