# Generated by Django 5.1 on 2025-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0010_alter_usermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('Pt', 'Patient')], default='Pt', max_length=20),
        ),
    ]
