# Generated by Django 5.1 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0013_alter_blogs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.FileField(blank=True, upload_to='blog/media'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
