# Generated by Django 5.1 on 2025-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0014_blogs_summary_alter_blogs_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.FileField(blank=True, upload_to='media/blog'),
        ),
    ]
