# Generated by Django 5.1 on 2025-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0015_alter_blogs_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.FileField(blank=True, upload_to='blog'),
        ),
    ]
