# Generated by Django 5.1 on 2025-05-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoleAccess_app', '0017_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
